name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=donut&theme=transparent&langs_count=5&hide_border=true
          path: .github/profile/top-langs.svg
          token: ${{ secrets.GRS_TOKEN }}

      - name: Commit card
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .github/profile/top-langs.svg
          git commit -m "Update top languages card" || exit 0
          git push

